packages:
  - apps/*
  - packages/*
catalog:
  dotenv: ^17.2.2
  zod: ^4.1.13
  typescript: ^5
  "@cloudflare/workers-types": ^4.20250822.0
  hono: ^4.8.2
  "@orpc/server": ^1.12.2
  "@orpc/openapi": ^1.12.2
  "@orpc/zod": ^1.12.2
  better-auth: 1.4.5
  "@orpc/client": ^1.12.2
  "@libsql/client": 0.15.15
  libsql: 0.5.22
